import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:billberrylite/core/di/service_locator.dart';
import 'package:billberrylite/data/models/restaurant/db/attendance_model.dart';
import 'package:billberrylite/util/color.dart';
import 'package:billberrylite/util/common/app_responsive.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:billberrylite/domain/services/retail/store_settings_service.dart';
import 'package:billberrylite/domain/services/common/report_export_service.dart';
import 'package:billberrylite/presentation/widget/componets/common/primary_app_bar.dart';
import 'staff_attendance_detail_screen.dart';

class AttendanceReportScreen extends StatefulWidget {
  const AttendanceReportScreen({super.key});

  @override
  State<AttendanceReportScreen> createState() => _AttendanceReportScreenState();
}

class _AttendanceReportScreenState extends State<AttendanceReportScreen> {
  DateTime _selectedMonth = DateTime.now();
  List<AttendanceModel> _records = [];
  bool _isLoading = true;

  Future<void> _printReport() async {
    final storeName = await StoreSettingsService().getStoreName() ?? 'Restaurant';
    final monthName = _monthName(_selectedMonth.month);
    final year = _selectedMonth.year;
    
    final font = await PdfGoogleFonts.poppinsRegular();
    final boldFont = await PdfGoogleFonts.poppinsBold();

    final allStaff = _staffNames;
    final periodEnd = (_selectedMonth.year == DateTime.now().year &&
            _selectedMonth.month == DateTime.now().month)
        ? DateTime.now()
        : DateTime(_selectedMonth.year, _selectedMonth.month + 1, 0);
    final workingDays = _workingDaysInPeriod(_selectedMonth, periodEnd);

    await Printing.layoutPdf(
      name: 'Attendance_Report_${monthName}_$year',
      onLayout: (PdfPageFormat format) async {
        final doc = pw.Document();
        doc.addPage(
          pw.MultiPage(
            pageFormat: format,
            margin: const pw.EdgeInsets.all(32),
            theme: pw.ThemeData.withFont(base: font, bold: boldFont),
            header: (pw.Context context) {
              return pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Center(
                    child: pw.Text(storeName, style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                  ),
                  pw.SizedBox(height: 8),
                  pw.Center(
                    child: pw.Text('Monthly Attendance Report - $monthName $year', style: const pw.TextStyle(fontSize: 16)),
                  ),
                  pw.SizedBox(height: 20),
                ],
              );
            },
            build: (pw.Context context) {
              return [
                pw.TableHelper.fromTextArray(
                  context: context,
                  border: pw.TableBorder.all(color: PdfColors.grey400, width: 0.5),
                  headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
                  headerDecoration: const pw.BoxDecoration(color: PdfColors.blueGrey800),
                  cellHeight: 30,
                  cellAlignments: {
                    0: pw.Alignment.centerLeft,
                    1: pw.Alignment.center,
                    2: pw.Alignment.center,
                    3: pw.Alignment.centerRight,
                  },
                  headers: ['Staff Name', 'Days Present', 'Days Absent', 'Total Hours Worked'],
                  data: allStaff.map((name) {
                    final presentDays = _presentDays(name);
                    final absentDays = (workingDays - presentDays).clamp(0, workingDays);
                    final totalMins = _totalMinutes(name);
                    
                    final h = totalMins ~/ 60;
                    final m = totalMins % 60;
                    final formattedHours = '${h}h ${m}m';

                    return [
                      name,
                      presentDays.toString(),
                      absentDays.toString(),
                      formattedHours,
                    ];
                  }).toList(),
                ),
                pw.SizedBox(height: 20),
                pw.Center(child: pw.Text('Generated by Bill Berry Lite', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600))),
              ];
            },
          ),
        );
        return doc.save();
      },
    );
  }

  @override
  void initState() {
    super.initState();
    // Normalize to first day of month
    _selectedMonth = DateTime(DateTime.now().year, DateTime.now().month, 1);
    _load();
  }

  Future<void> _pickMonth() async {
    final picked = await showDatePicker(
      context: context,
      initialDate: _selectedMonth,
      firstDate: DateTime(2020),
      lastDate: DateTime.now(),
      initialDatePickerMode: DatePickerMode.year,
      helpText: 'SELECT MONTH',
    );
    if (picked != null) {
      setState(() {
        _selectedMonth = DateTime(picked.year, picked.month, 1);
      });
      _load();
    }
  }

  void _nextMonth() {
    final next = DateTime(_selectedMonth.year, _selectedMonth.month + 1, 1);
    if (next.isBefore(DateTime.now()) || (next.year == DateTime.now().year && next.month == DateTime.now().month)) {
      setState(() {
        _selectedMonth = next;
      });
      _load();
    }
  }

  void _prevMonth() {
    setState(() {
      _selectedMonth = DateTime(_selectedMonth.year, _selectedMonth.month - 1, 1);
    });
    _load();
  }

  Future<void> _load() async {
    setState(() => _isLoading = true);
    
    final startOfMonth = _selectedMonth;
    final endOfMonth = DateTime(_selectedMonth.year, _selectedMonth.month + 1, 0, 23, 59, 59);
    
    final result = await attendanceStore.getRecordsBetweenDates(startOfMonth, endOfMonth);
      
    setState(() {
      _records = result;
      _isLoading = false;
    });
  }

  // Operating days between two dates, inclusive. Restaurants run 7 days a week,
  // so every calendar day counts as a working day (not just Mon–Fri).
  int _workingDaysInPeriod(DateTime start, DateTime end) {
    int count = 0;
    var d = DateTime(start.year, start.month, start.day);
    final last = DateTime(end.year, end.month, end.day);
    while (!d.isAfter(last)) {
      count++;
      d = d.add(const Duration(days: 1));
    }
    return count;
  }

  // All unique staff names
  List<String> get _staffNames {
    // Include all active staff from staffStore so absent staff show up
    final fromRecords = _records.map((r) => r.staffName).toSet();
    final fromStore = staffStore.staff
        .where((s) => s.isActive)
        .map((s) => '${s.firstName} ${s.lastName}'.trim())
        .toSet();
    return {...fromRecords, ...fromStore}.toList()..sort();
  }

  int _presentDays(String name) {
    // Count unique dates this staff has records for in this month
    return _records.where((r) => r.staffName == name).map((r) => r.date).toSet().length;
  }

  int _totalMinutes(String name) {
    final now = DateTime.now();
    return _records
        .where((r) => r.staffName == name)
        .fold(0, (s, r) {
          if (r.totalMinutes != null) return s + r.totalMinutes!;
          if (!r.isOpen) return s;
          final gross = now.difference(r.clockIn).inMinutes;
          final breaks = (r.breakTotalMinutes ?? 0) +
              (r.isOnBreak && r.breakStartTime != null
                  ? now.difference(r.breakStartTime!).inMinutes
                  : 0);
          final active = gross - breaks;
          return s + (active < 0 ? 0 : active);
        });
  }

  String _fmtMins(int mins) {
    final h = mins ~/ 60;
    final m = mins % 60;
    if (h == 0 && m == 0) return '0m';
    if (h == 0) return '${m}m';
    return '${h}h ${m}m';
  }

  String _monthName(int m) {
    const months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
    return months[m - 1];
  }

  Future<void> _doExport(BuildContext context) async {
    final allStaff = _staffNames;
    final isCurrentMonth = _selectedMonth.year == DateTime.now().year &&
        _selectedMonth.month == DateTime.now().month;
    final periodEnd = isCurrentMonth
        ? DateTime.now()
        : DateTime(_selectedMonth.year, _selectedMonth.month + 1, 0);
    final workingDays = _workingDaysInPeriod(_selectedMonth, periodEnd);

    final headers = ['Staff Name', 'Role', 'Days Present', 'Days Absent', 'Total Hours'];
    final data = allStaff.map((name) {
      final presentDays = _presentDays(name);
      final absentDays = (workingDays - presentDays).clamp(0, workingDays);
      final totalMins = _totalMinutes(name);
      final staffModel = staffStore.staff
          .where((s) => '${s.firstName} ${s.lastName}'.trim() == name)
          .firstOrNull;
      final role = staffModel?.isCashier ??
          (_records.where((r) => r.staffName == name).firstOrNull?.staffRole ?? '');
      return <dynamic>[name, role, presentDays, absentDays, _fmtMins(totalMins)];
    }).toList();

    await ReportExportService.showExportDialog(
      context: context,
      fileName: 'attendance_${_monthName(_selectedMonth.month)}_${_selectedMonth.year}',
      reportTitle: 'Monthly Attendance — ${_monthName(_selectedMonth.month)} ${_selectedMonth.year}',
      headers: headers,
      data: data,
      summary: {
        'Month': '${_monthName(_selectedMonth.month)} ${_selectedMonth.year}',
        'Total Staff': '${allStaff.length}',
        'Working Days': '$workingDays',
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    final allStaff = _staffNames;
    
    final isCurrentMonth = _selectedMonth.year == DateTime.now().year && 
                           _selectedMonth.month == DateTime.now().month;

    final periodEnd = isCurrentMonth
        ? DateTime.now()
        : DateTime(_selectedMonth.year, _selectedMonth.month + 1, 0);
    final workingDays = _workingDaysInPeriod(_selectedMonth, periodEnd);

    return Scaffold(
      backgroundColor: const Color(0xFFF7F8FA),
      appBar: buildPrimaryAppBar(
        title: 'Monthly Attendance',
        titleFontSize: 18,
        centerTitle: true,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () => Navigator.pop(context),
        ),
        actions: [
          IconButton(
            icon: const Icon(Icons.file_download_outlined),
            onPressed: () => _doExport(context),
            tooltip: 'Export',
          ),
          IconButton(
            icon: const Icon(Icons.print),
            onPressed: _printReport,
            tooltip: 'Print',
          ),
        ],
      ),
      body: Column(
        children: [
          // ── Month selector ───────────────────────────────────────────
          Container(
            color: Colors.white,
            padding: EdgeInsets.symmetric(
                horizontal: AppResponsive.largeSpacing(context),
                vertical: AppResponsive.mediumSpacing(context)),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                IconButton(
                  icon: Icon(Icons.chevron_left, color: AppColors.primary),
                  onPressed: _prevMonth,
                ),
                GestureDetector(
                  onTap: _pickMonth,
                  child: Container(
                    padding: EdgeInsets.symmetric(
                        horizontal: AppResponsive.largeSpacing(context),
                        vertical: AppResponsive.smallSpacing(context)),
                    decoration: BoxDecoration(
                      color: AppColors.primary.withOpacity(0.1),
                      borderRadius: BorderRadius.circular(AppResponsive.borderRadius(context)),
                    ),
                    child: Row(
                      children: [
                        Icon(Icons.calendar_month,
                            size: AppResponsive.smallIconSize(context),
                            color: AppColors.primary),
                        SizedBox(width: AppResponsive.smallSpacing(context)),
                        Text(
                          '${_monthName(_selectedMonth.month)} ${_selectedMonth.year}',
                          style: GoogleFonts.poppins(
                            fontSize: AppResponsive.bodyFontSize(context),
                            fontWeight: FontWeight.w600,
                            color: AppColors.primary,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                IconButton(
                  icon: Icon(Icons.chevron_right,
                      color: isCurrentMonth ? Colors.grey.shade300 : AppColors.primary),
                  onPressed: isCurrentMonth ? null : _nextMonth,
                ),
              ],
            ),
          ),

          if (_isLoading)
            const Expanded(child: Center(child: CircularProgressIndicator()))
          else if (allStaff.isEmpty)
            Expanded(
              child: Center(
                child: Text('No staff data found',
                    style:
                        GoogleFonts.poppins(color: Colors.grey.shade500)),
              ),
            )
          else
            Expanded(
              child: ListView.separated(
                padding: EdgeInsets.all(AppResponsive.largeSpacing(context)),
                itemCount: allStaff.length,
                separatorBuilder: (_, __) => SizedBox(height: AppResponsive.smallSpacing(context)),
                itemBuilder: (_, i) {
                  final name = allStaff[i];
                  
                  final presentDays = _presentDays(name);
                  final absentDays = (workingDays - presentDays).clamp(0, workingDays);
                  final totalMins = _totalMinutes(name);

                  // Role from staff store or first record
                  final staffModel = staffStore.staff
                      .where((s) =>
                          '${s.firstName} ${s.lastName}'.trim() == name)
                      .firstOrNull;
                  final role = staffModel?.isCashier ?? 
                      (_records.where((r) => r.staffName == name).firstOrNull?.staffRole ?? '');

                  final staffRecords = _records.where((r) => r.staffName == name).toList();

                  return GestureDetector(
                    onTap: () {
                      Navigator.push(
                        context,
                        MaterialPageRoute(
                          builder: (_) => StaffAttendanceDetailScreen(
                            staffName: name,
                            staffRole: role,
                            from: _selectedMonth,
                            to: DateTime(_selectedMonth.year, _selectedMonth.month + 1, 0, 23, 59, 59),
                            initialRecords: staffRecords,
                          ),
                        ),
                      );
                    },
                    child: Container(
                      padding: EdgeInsets.all(AppResponsive.largeSpacing(context)),
                      decoration: BoxDecoration(
                        color: Colors.white,
                        borderRadius: BorderRadius.circular(AppResponsive.borderRadius(context)),
                        border: Border.all(color: Colors.grey.shade200),
                        boxShadow: [
                          BoxShadow(
                            color: Colors.black.withOpacity(0.02),
                            blurRadius: 4,
                            offset: const Offset(0, 2),
                          )
                        ],
                      ),
                      child: Row(
                        children: [
                          // Avatar
                          Container(
                            width: AppResponsive.getValue<double>(context,
                                mobile: 44, tablet: 48, desktop: 52),
                            height: AppResponsive.getValue<double>(context,
                                mobile: 44, tablet: 48, desktop: 52),
                            decoration: BoxDecoration(
                              color: AppColors.primary.withOpacity(0.1),
                              shape: BoxShape.circle,
                            ),
                            child: Center(
                              child: Text(
                                name.isNotEmpty ? name[0].toUpperCase() : '?',
                                style: GoogleFonts.poppins(
                                    fontSize: AppResponsive.bodyFontSize(context),
                                    fontWeight: FontWeight.w700,
                                    color: AppColors.primary),
                              ),
                            ),
                          ),
                          SizedBox(width: AppResponsive.mediumSpacing(context)),
                          // Name + role
                          Expanded(
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Text(name,
                                    style: GoogleFonts.poppins(
                                        fontSize: AppResponsive.bodyFontSize(context),
                                        fontWeight: FontWeight.w700)),
                                Text(role,
                                    style: GoogleFonts.poppins(
                                        fontSize: AppResponsive.captionFontSize(context),
                                        color: Colors.grey.shade500)),
                                SizedBox(height: AppResponsive.smallSpacing(context)),
                                Row(
                                  children: [
                                    _miniChip(context, '${presentDays}P', Colors.green.shade600),
                                    SizedBox(width: AppResponsive.smallSpacing(context) * 0.5),
                                    _miniChip(context, '${absentDays}A',
                                        absentDays > 0 ? Colors.red.shade400 : Colors.grey.shade400),
                                  ],
                                ),
                              ],
                            ),
                          ),
                          // Hours + arrow
                          Column(
                            crossAxisAlignment: CrossAxisAlignment.end,
                            children: [
                              Text(
                                'Total Hours',
                                style: GoogleFonts.poppins(
                                    fontSize: AppResponsive.captionFontSize(context),
                                    color: Colors.grey.shade500),
                              ),
                              const SizedBox(height: 2),
                              Text(
                                _fmtMins(totalMins),
                                style: GoogleFonts.poppins(
                                    fontSize: AppResponsive.bodyFontSize(context),
                                    fontWeight: FontWeight.w700,
                                    color: AppColors.primary),
                              ),
                              const SizedBox(height: 4),
                              Icon(Icons.arrow_forward_ios,
                                  size: AppResponsive.smallIconSize(context),
                                  color: Colors.grey.shade400),
                            ],
                          ),
                        ],
                      ),
                    ),
                  );
                },
              ),
            ),
        ],
      ),
    );
  }

  Widget _miniChip(BuildContext context, String label, Color color) {
    return Container(
      padding: EdgeInsets.symmetric(
          horizontal: AppResponsive.smallSpacing(context),
          vertical: 2),
      decoration: BoxDecoration(
        color: color.withOpacity(0.1),
        borderRadius: BorderRadius.circular(4),
      ),
      child: Text(label,
          style: GoogleFonts.poppins(
              fontSize: AppResponsive.captionFontSize(context),
              fontWeight: FontWeight.w700,
              color: color)),
    );
  }
}